package org.selvinsource.hazelcast_jet_ml;

import static java.nio.charset.StandardCharsets.UTF_8;

import java.io.BufferedReader;
import java.io.Closeable;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.selvinsource.hazelcast_jet_ml.ml.clustering.KMeans;
import org.selvinsource.hazelcast_jet_ml.ml.pipeline.Estimator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class JetMLDemo 
{

	private static final Logger LOGGER = LoggerFactory.getLogger(JetMLDemo.class);
	
    public enum EstimatorType {
        KMeans;
    }

    public static void main( String[] args )
    {
        if(args.length != 1){
            System.out.println("Please select an estimator: KMeans");
            return;
        }
        switch(EstimatorType.valueOf(args[0])) {
        case KMeans:
            System.out.println(EstimatorType.KMeans + " selected");
            runKMeansJetMLPipelineDemo();
            break;
        default:
            System.out.println("Estimator selected not implemented");
            return;
        }
    }

    private static void runKMeansJetMLPipelineDemo() {
    	// Read the iris.csv file into a list of double[]
 
    	// Note: skip(1) removes the header, import also the last column (the class), to compare it with the one predicted by the clustering algorithm which is unsupervised (it doesn't use the class)
    	List<String[]> inputDatasetWithClass = getFileContent("/datasets/iris.csv").skip(1).map(line -> 
    		line.split(",")
    	).collect(Collectors.toList());

    	// Note: convert attributes into doubles, limit(attributes.length-1) removes the class column
    	List<double[]> inputDataset = inputDatasetWithClass.stream().map(
    			attr -> Arrays.stream(attr).limit(attr.length-1).mapToDouble(Double::parseDouble).toArray()
		).collect(Collectors.toList());
    	
    	// Create a KMeans estimator with k = 3 (ideally it should match the known class: Iris-setosa, Iris-versicolor, Iris-virginica)
		Estimator<double[]> estimator = new KMeans(3, 20);
		// Hazelcast Get ML Pipeline
		// Train using inputDataset and test using the same inputDataset to see if the predicted classes are comparable to the known ones
		List<double[]> outputDataset = estimator.fit(inputDataset).transform(inputDataset);    	
		
		// Print results comparing predicted (last double which is 0, 1 or 2) and the known class
		LOGGER.info("Print output with predicted cluster and orginal known class:");
		AtomicInteger index = new AtomicInteger();
		outputDataset.stream().forEach(
				i -> LOGGER.info(Arrays.toString(i) + " known as " + inputDatasetWithClass.get(index.getAndIncrement())[4])
		);
		
		LOGGER.info("Summary of orginal class:");
        Map<String, Long> summaryOriginal = inputDatasetWithClass.stream().collect(
        		Collectors.groupingBy(i -> i[4], Collectors.counting())
        );
        LOGGER.info(summaryOriginal.toString());
		
        LOGGER.info("Summary of clustered instances:");
        Map<Double, Long> summaryClustered = outputDataset.stream().collect(
        		Collectors.groupingBy(i -> i[4], Collectors.counting())
        );
        LOGGER.info(summaryClustered.toString());
        
        // Some comparison to another machine learning library
		LOGGER.info("Computed clusters are comparable to the one generated by Spark MLLib given the same input file: https://github.com/selvinsource/spark-pmml-exporter-validator/blob/master/src/main/resources/exported_pmml_models/kmeans.xml");
		
    }
    
    private static Stream<String> getFileContent(String fileName) {
    	final BufferedReader r = new BufferedReader(new InputStreamReader(JetMLDemo.class.getResourceAsStream(fileName), UTF_8));
    	return r.lines().onClose(() -> close(r));
    }    

    private static void close(Closeable c) {
    	try {
    		c.close();
    	} catch (IOException e) {
    		throw new RuntimeException(e);
    	}
    }    

}
